restoring some functions bringing back working root! WTF??? Where???

diff --git a/chargemon b/chargemon
--- a/chargemon
+++ b/chargemon
@@ -1,9 +1,27 @@
 #!/system/bin/sh
+#
+# Dual Recovery for many Sony Xperia devices!
+#
+# Author:
+#   [NUT]
+#
+# - Thanks go to DooMLoRD for the keycodes and a working example!
+# - My gratitude also goes out to Androxyde for his sometimes briliant
+#   ideas to simplify things while writing the scripts!
+#
+###########################################################################
 
 set +x
 _PATH="$PATH"
 export PATH="/system/xbin:/system/bin:/sbin"
 
+# Constants
+LOGDIR="XZDualRecovery"
+SECUREDIR="/system/.XZDualRecovery"
+PREPLOG="/tmp/${LOGDIR}/preperation.log"
+LOGFILE="XZDualRecovery.log"
+
+# Nodes setup
 BOOTREC_LED_RED="/sys/class/leds/$(/system/xbin/busybox ls -1 /sys/class/leds|/system/xbin/busybox grep red)/brightness"
 BOOTREC_LED_GREEN="/sys/class/leds/$(/system/xbin/busybox ls -1 /sys/class/leds|/system/xbin/busybox grep green)/brightness"
 BOOTREC_LED_BLUE="/sys/class/leds/$(/system/xbin/busybox ls -1 /sys/class/leds|/system/xbin/busybox grep blue)/brightness"
@@ -22,22 +40,7 @@ TEXECL(){
   echo "${_TIME} >> RET=${_RET}" >> ${PREPLOG}
   return ${_RET}
 }
-#86|87) TEXECL mount -t ntfs ${BOOTREC_EXTERNAL_SDCARD} /storage/sdcard1; return $?;;
-MOUNTSDCARD(){
-	case $* in
-		06|6|0B|b|0C|c|0E|e) TEXECL mount -t vfat ${BOOTREC_EXTERNAL_SDCARD} /storage/sdcard1; return $?;;
-		07|7) TEXECL insmod /system/lib/modules/nls_utf8.ko;
-		      TEXECL insmod /system/lib/modules/texfat.ko;
-		      TEXECL mount -t texfat ${BOOTREC_EXTERNAL_SDCARD} /storage/sdcard1;
-		      return $?;;
-		83) PTYPE=$(/system/xbin/busybox blkid ${BOOTREC_EXTERNAL_SDCARD} | /system/xbin/busybox awk -F' ' '{ print $NF }' | /system/xbin/busybox awk -F'[\"=]' '{ print $3 }');
-		    TEXECL mount -t $PTYPE ${BOOTREC_EXTERNAL_SDCARD} /storage/sdcard1;
-		    return $?;;
-		 *) return 1;;
-	esac
-	TECHOL "### MOUNTSDCARD did not run with a parameter!";
-	return 1;
-}
+
 SETLED() {
 	if [ "$1" = "on" ]; then
 
@@ -62,24 +65,102 @@ EXIT2CM(){
 	# Turn off LED
 	SETLED off
 
-	# Ending log
-	DATETIME=`/system/xbin/busybox date +"%d-%m-%Y %H:%M:%S"`
-	echo "STOP Dual Recovery STAGE 1 at ${DATETIME}" >> ${PREPLOG}
-
 	umount -l /storage/sdcard1
 
 	export PATH="${_PATH}"
 
 	exec /system/bin/chargemon.stock
 	exit 0
-} 
+}
 
-BUSYBOX="/system/xbin/busybox"
-NOGOODBUSYBOX="false"
+NOGOODBUSYBOX="true"
+# Busybox setup, chosing the one that supports lzcat, as it is vital for this recovery setup!
+if [ -x "/system/xbin/busybox" -a ! -n "${BUSYBOX}" ]; then
+	CHECK=`/system/xbin/busybox --list | /system/xbin/busybox grep lzcat | /system/xbin/busybox wc -l`
+	if [ "$CHECK" -gt "0" ]; then
+ 		BUSYBOX="/system/xbin/busybox"
+		NOGOODBUSYBOX="false"
+	fi
+fi
+# Fallback to the one in /system/bin, but only if it supports lzcat...
+if [ -x "/system/bin/busybox" -a "$NOGOODBUSYBOX" = "true" ]; then
+	CHECK=`/system/bin/busybox --list | /system/bin/busybox grep lzcat | /system/bin/busybox wc -l`
+	if [ "$CHECK" -gt "0" ]; then
+		BUSYBOX="/system/bin/busybox"
+		NOGOODBUSYBOX="false"
+	fi
+fi
 
 #https://github.com/android/platform_system_core/commit/e18c0d508a6d8b4376c6f0b8c22600e5aca37f69
 #The busybox in all of the recoveries has not yet been patched to take this in account.
-${BUSYBOX} blockdev --setrw $(${BUSYBOX} find /dev/block/platform/msm_sdcc.1/by-name/ -iname "system"
+${BUSYBOX} blockdev --setrw $(${BUSYBOX} find /dev/block/platform/msm_sdcc.1/by-name/ -iname "system")
+
+# If no good busybox has been found, we will replace the one in xbin
+# This was never so important but with the release of the JB4.3 ROM on the Z1, Z1 Compact and Z Ultra
+# this missing busybox will break full root provided by XZDualRecovery making these
+# user errors that more painful.
+if [ "$NOGOODBUSYBOX" = "true" -a -d "$SECUREDIR" ]; then
+
+	$SECUREDIR/busybox mount -o remount,rw /system
+	$SECUREDIR/busybox cp $SECUREDIR/busybox /system/xbin/
+	chmod 755 /system/xbin/busybox
+	BUSYBOX="/system/xbin/busybox"
+	${BUSYBOX} mount -o remount,ro /system
+
+fi
+
+MADESECDIR="false"
+if [ ! -d "$SECUREDIR" -a -x "${BUSYBOX}" ]; then
+
+	${BUSYBOX} mount -o remount,rw /system
+	${BUSYBOX} mkdir $SECUREDIR
+	if [ "$?" = "0" ]; then
+		MADESECDIR="true"
+		${BUSYBOX} cp ${BUSYBOX} $SECUREDIR/
+		${BUSYBOX} mount -o remount,ro /system
+	fi
+
+fi
+
+# We can actually safely asume a busybox exists in /system/xbin (as XZDualRecovery installs one there)
+${BUSYBOX} mount -o remount,rw rootfs /
+MADETMP="false"
+if [ ! -d "/tmp" ]; then
+
+	mkdir /tmp
+	${BUSYBOX} mount -t tmpfs tmpfs /tmp
+	if [ "$?" = "0" ]; then
+		MADETMP="true"
+	fi
+
+fi
+${BUSYBOX} mkdir /tmp/XZDualRecovery
+${BUSYBOX} mount -o remount,ro rootfs /
+
+# Kickstarting log
+DATETIME=`${BUSYBOX} date +"%d-%m-%Y %H:%M:%S"`
+echo "START Dual Recovery at ${DATETIME}: STAGE 1." > ${PREPLOG}
+
+# If $SECUREDIR was created, it will be noted in the log.
+if [ "$MADESECDIR" = "true" ]; then
+
+	echo "Created $SECUREDIR!" >> ${PREPLOG}
+
+fi
+
+# If /tmp was created, it will be noted in the log.
+if [ "$MADETMP" = "true" ]; then
+
+	echo "Created /tmp!" >> ${PREPLOG}
+
+fi
+
+# If the busybox binary has been replaced by a known good one, this will let us know in the log.
+if [ "$NOGOODBUSYBOX" = "true" ]; then
+
+	echo "Replaced busybox in /system/xbin!" >> ${PREPLOG}
+
+fi
 
 if [ -x "${BUSYBOX}" ]; then
 
@@ -136,6 +217,13 @@ if [ -x "${BUSYBOX}" ]; then
 
 fi
 
+# Create mountpoint if it doesn't exist
+if [ ! -d /storage/sdcard1 ]; then
+	TEXECL mount -o remount,rw rootfs /
+	TEXECL mkdir -p /storage/sdcard1
+	TEXECL mount -o remount,ro rootfs /
+fi
+
 # As a precaution, give users a way out. This works best if the user has an external sdcard.
 if [ -f "${DRPATH}/donotrun" ]; then
 
@@ -145,5 +233,40 @@ if [ -f "${DRPATH}/donotrun" ]; then
 
 fi
 
-EXIT2CM
+if [ ! -d "/system/etc/init.d" ]; then
+	TECHOL "No init.d directory found, creating it now!"
+	TECHOL "To enable init.d support, set dr.enable.initd to true in XZDR.prop!"
+	mkdir /system/etc/init.d
+fi
 
+if [ -e "/sbin/init.sh" -a "$EVENTNODE" != "none" ]; then
+	echo "Will be calling /sbin/init.sh with arguments '$DRPATH' and '$LOGFILE'" >> ${PREPLOG}
+fi
+
+# Ending log
+DATETIME=`${BUSYBOX} date +"%d-%m-%Y %H:%M:%S"`
+echo "STOP Dual Recovery STAGE 1 at ${DATETIME}, starting stage 2!" >> ${PREPLOG}
+
+# Copy the preperation log to the main log directory, easy to find for the noobish users...
+cp ${PREPLOG} ${DRPATH}/
+
+########
+#
+#
+# Preperations all done, lets continue to recovery!
+#
+#
+#######################################################################
+
+# One last failsafe...
+if [ -e "/sbin/init.sh" -a "$EVENTNODE" != "none" ]; then
+
+	export PATH="${_PATH}"
+
+	exec /sbin/init.sh $DRPATH $LOGFILE
+
+else
+
+	EXIT2CM
+
+fi
